#8 proximity based timer
LeonUwe/IAV_Distortion pull request #21
Opened 2024-11-01 15:34 UTC by Einfachmario45

2024-11-01 20:38 UTC, LeonUwe commented
The hack-button is never made invisible again. Once a driver has completed the proximity timer, they'll have the button for the rest of their time playing. It should disappear when they leave the proximity of the hackable vehicle.

2024-11-01 20:42 UTC, LeonUwe commented
There is a lot of reformatting going on in the .html and .css files. This makes reviewing them quite difficult. In the future please isolate the reformatting in its own commits or refrain from doing it completely.

2024-11-01 20:50 UTC, LeonUwe commented
Apart from the mentioned issues, the functionality has been implemented nicely.

2024-11-01 20:58 UTC, LeonUwe commented
I found a little bug:

![image](https://github.com/user-attachments/assets/755cca20-cacc-4f3b-82dc-c555d0f6c19f)

This was caused by kicking a player out of the race (manually or by being idle). This message is printed to the console repeatedly until the player reconnects.

Should be fixable by a is None check in DriverUI.py line 258.

2024-11-02 13:04 UTC, Einfachmario45 commented
> 

Sorry about the reformatting. I have Prettier installed, and it reformats automatically.

2024-11-02 16:03 UTC, LeonUwe requested changes

2024-11-02 18:10 UTC, LeonUwe commented on src/UserInterface/CarMap.py
> +                        self._environment_manager.get_vehicle_by_vehicle_id(vehicle_id).vehicle_in_proximity = vehicle.vehicle_id
Fixed in [833673a](https://github.com/LeonUwe/IAV_Distortion/pull/21/commits/833673a6a132f58e4fd6fc6709917b12da0a8d0d)

2024-11-02 18:11 UTC, LeonUwe commented on src/UserInterface/CarMap.py
> +    def check_vehicle_proximity(self,vehicle_id: str, position: dict,) -> None:
[833673a](https://github.com/LeonUwe/IAV_Distortion/pull/21/commits/833673a6a132f58e4fd6fc6709917b12da0a8d0d)

2024-11-02 18:11 UTC, LeonUwe commented on src/UserInterface/DriverUI.py
> +    async def __send_proximity_vehicle(self, player: str):
[833673a](https://github.com/LeonUwe/IAV_Distortion/pull/21/commits/833673a6a132f58e4fd6fc6709917b12da0a8d0d)

2024-11-02 18:11 UTC, LeonUwe commented on src/UserInterface/DriverUI.py
> +    async def __check_driver_proximity_timer(self, player: str):
[833673a](https://github.com/LeonUwe/IAV_Distortion/pull/21/commits/833673a6a132f58e4fd6fc6709917b12da0a8d0d)

2024-11-02 18:11 UTC, LeonUwe commented on src/UserInterface/templates/driver_index.html
> +      });
[833673a](https://github.com/LeonUwe/IAV_Distortion/pull/21/commits/833673a6a132f58e4fd6fc6709917b12da0a8d0d)

2024-11-03 18:10 UTC, LeonUwe approved these changes

2024-11-03 21:13 UTC, merged