Added Basic Bot Tests
LeonUwe/IAV_Distortion pull request #71
Opened 2024-12-15 15:22 UTC by Max9786

2024-12-15 15:48 UTC, LeonUwe commented
Looks fine to me. @Einfachmario45 what do you think?

2024-12-15 16:49 UTC, Einfachmario45 requested changes

2024-12-15 16:49 UTC, Einfachmario45 commented on test/UnitTest/UserInterface/CarMap_Test.py
There is a self.assertIsNone(), pls use that instead.

2024-12-17 12:05 UTC, Einfachmario45 approved these changes

2024-12-17 12:34 UTC, merged